# Generated by Django 3.2.9 on 2021-12-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker_chat', '0002_auto_20211214_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='accuracy',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='chatbot_id',
            field=models.TextField(default=''),
        ),
    ]
